### ISSUE TITLE
New IRIS API to enable the use of HPC libraries

### ISSUE THREAD

**Issue by pedrovalerolara** [ORNL/iris#8]
I attach a couple of slides where we can see the current API using "task kernel" in the first slide and the proposed API to enable IRIS to use HPC libraries and benefit from IRIS memory management.
[NewIrisAPI.pptx](https://github.com/ORNL/iris/files/8088874/NewIrisAPI.pptx)

**Comment by BeauJoh** [comment]
Without giving this enough thought, I'd start by copying task.h and task.cpp from src/runtime.
I think since this doesn't really run any commands these are responsible for either explicit operations you don't want to expose (memory transfers and kernel runs), this is probably the place to put this level of abstraction.
It would need a unique name in the API, like iris_agent_task---or some other more appropriate name to denote this still honors/uses IRIS task dependencies but is farmed out to an external entity.
It wouldn't handle any commands or subtasks, so this would be a minimal (copied version of task) with alot of stuff stripped away.
It would still need to track the device it is assigned to---and this may get messy interfacing with device selection in these 3rd party libraries and APIs.
Perhaps, it would only actually ever execute the host-level "kernel"/api function wrapper as a fork or p-thread.

I may be able to help implement it next week, but I am trying to submit a paper, otherwise definitely the week after.

**Comment by pedrovalerolara** [comment]
Hi Beau! Thanks for your comments.
I just realized that it would be also necessary to include SGEMM_idx in the new API, since that is used to customize the policies.
I changed the slides to include that (see [attachment).
Thanks!
Pedro 
[NewIrisAPI.pptx](https://github.com/ORNL/iris/files/8119910/NewIrisAPI.pptx)
