### ISSUE TITLE
develop IRIS test framework for CI/CD

### ISSUE THREAD

**Issue by vetter** [ORNL/iris#9]
perhaps use CTEST or similar framework.

**Comment by Geekdude** [comment]
[Doctest](https://github.com/doctest/doctest), is another CPP testing framework.

**Comment by miniskar** [comment]
Do we have any code coverage tool integrated with unit test? 
I am thinking of one open source tool SonarQube.

**Comment by Geekdude** [comment]
[CTest ](https://gitlab.kitware.com/cmake/community/-/wikis/doc/ctest/Testing-With-CTest#:~:text=CTest%20is%20a%20testing%20tool,CDash%20or%20Dart%20dashboard%20system.) or [GoogleTest](https://github.com/google/googletest).

**Comment by Geekdude** [comment]
I was trying out CMake, Doctest, and GCov and I created this demo repository. https://code.ornl.gov/7ry/cmake-doctest-gcov

**Comment by Geekdude** [comment]
A basic CTest testbed is created at https://code.ornl.gov/brisbane/iris/-/pipelines with CI-Runners to test it.

Currently, the following tests are failing.
![image](https://user-images.githubusercontent.com/2541055/163835345-6823ca1e-e8ab-43aa-ab73-db5a83f8a921.png)

Test 16 builds and the test is disabled since it hangs.

**Comment by vetter** [comment]
closing this issue and moving discussions to internal dev version.
